//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace BTS.Common.CAS {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yale.edu/tp/cas")]
    [System.Xml.Serialization.XmlRootAttribute("serviceResponse", Namespace="http://www.yale.edu/tp/cas", IsNullable=false)]
    public partial class ServiceResponseType {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("authenticationFailure", typeof(AuthenticationFailureType))]
        [System.Xml.Serialization.XmlElementAttribute("authenticationSuccess", typeof(AuthenticationSuccessType))]
        [System.Xml.Serialization.XmlElementAttribute("proxyFailure", typeof(ProxyFailureType))]
        [System.Xml.Serialization.XmlElementAttribute("proxySuccess", typeof(ProxySuccessType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yale.edu/tp/cas")]
    public partial class AuthenticationFailureType {
        
        private string codeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yale.edu/tp/cas")]
    public partial class ProxyFailureType {
        
        private string codeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yale.edu/tp/cas")]
    public partial class ProxySuccessType {
        
        private string proxyTicketField;
        
        /// <remarks/>
        public string proxyTicket {
            get {
                return this.proxyTicketField;
            }
            set {
                this.proxyTicketField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yale.edu/tp/cas")]
    public partial class AttributesType {
        
        private System.DateTime authenticationDateField;
        
        private bool longTermAuthenticationRequestTokenUsedField;
        
        private bool isFromNewLoginField;
        
        private string[] memberOfField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public System.DateTime authenticationDate {
            get {
                return this.authenticationDateField;
            }
            set {
                this.authenticationDateField = value;
            }
        }
        
        /// <remarks/>
        public bool longTermAuthenticationRequestTokenUsed {
            get {
                return this.longTermAuthenticationRequestTokenUsedField;
            }
            set {
                this.longTermAuthenticationRequestTokenUsedField = value;
            }
        }
        
        /// <remarks/>
        public bool isFromNewLogin {
            get {
                return this.isFromNewLoginField;
            }
            set {
                this.isFromNewLoginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("memberOf")]
        public string[] memberOf {
            get {
                return this.memberOfField;
            }
            set {
                this.memberOfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yale.edu/tp/cas")]
    public partial class AuthenticationSuccessType {
        
        private string userField;
        
        private AttributesType attributesField;
        
        private string proxyGrantingTicketField;
        
        private string[] proxiesField;
        
        /// <remarks/>
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public AttributesType attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
        
        /// <remarks/>
        public string proxyGrantingTicket {
            get {
                return this.proxyGrantingTicketField;
            }
            set {
                this.proxyGrantingTicketField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("proxy", IsNullable=false)]
        public string[] proxies {
            get {
                return this.proxiesField;
            }
            set {
                this.proxiesField = value;
            }
        }
    }
}
